export const EXCURSIONS = [
  {
    id: 1,
    image: '/backgrounds/image 2.jpg',
    title: 'City Tour in Kyiv',
    description: 'Explore the heart of Kyiv with a local guide.',
    location: 'Kyiv, Ukraine',
    date: '2024-12-10',
    price: 50,
    likes: 200,
    dislikes: 5,
  },
  {
    id: 2,
    image: '/backgrounds/image 3.jpg',
    title: 'Lviv Old Town Tour',
    description: 'Discover the charming streets of Lviv.',
    location: 'Lviv, Ukraine',
    date: '2024-12-15',
    price: 45,
    likes: 150,
    dislikes: 3,
  },
  {
    id: 3,
    image: '/backgrounds/image 4.jpg',
    title: 'Lviv Church Tour',
    description: 'Visit the historic churches of Lviv.',
    location: 'Lviv, Ukraine',
    date: '2024-12-16',
    price: 100,
    likes: 250,
    dislikes: 10,
  },
  {
    id: 4,
    image: '/backgrounds/image 5.jpg',
    title: 'Kamianets Podilskyi Castle Tour',
    description: 'Explore the historic castle of Kamianets Podilskyi.',
    location: 'Kamianets Podilskyi, Ukraine',
    date: '2024-12-17',
    price: 75,
    likes: 175,
    dislikes: 8,
  },
  {
    id: 5,
    image: '/backgrounds/image 6.jpg',
    title: 'Lutsk Old Town Tour',
    description: 'Discover the charming streets of Lutsk.',
    location: 'Lutsk, Ukraine',
    date: '2024-12-14',
    price: 40,
    likes: 125,
    dislikes: 2,
  },
  {
    id: 6,
    image: '/backgrounds/image 7.jpg',
    title: 'Lutsk Castle Tour',
    description: 'Visit the historic castle of Lutsk.',
    location: 'Lutsk, Ukraine',
    date: '2024-12-13',
    price: 80,
    likes: 180,
    dislikes: 9,
  },
  {
    id: 7,
    image: '/backgrounds/image 8.jpg',
    title: 'Pidhirtsi Castle Tour',
    description: 'Visit the historic castle of Pidhirtsi.',
    location: 'Pidhirtsi, Ukraine',
    date: '2024-12-12',
    price: 90,
    likes: 220,
    dislikes: 12,
  },
];
